CREATE DATABASE turg;
CREATE USER turg_user WITH ENCRYPTED PASSWORD 'pass';
\c turg
GRANT ALL ON ALL TABLES IN SCHEMA public TO turg_user;
GRANT ALL PRIVILEGES ON DATABASE turg TO turg_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO turg_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO turg_user;
